const D = 'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons';

export const TECH_ICON: Record<string, string> = {
  'Python':           `${D}/python/python-original.svg`,
  'JavaScript':       `${D}/javascript/javascript-original.svg`,
  'TypeScript':       `${D}/typescript/typescript-original.svg`,
  'Java':             `${D}/java/java-original.svg`,
  'PHP':              `${D}/php/php-original.svg`,
  'Dart':             `${D}/dart/dart-original.svg`,
  'Kotlin':           `${D}/kotlin/kotlin-original.svg`,
  'Swift':            `${D}/swift/swift-original.svg`,
  'HTML':             `${D}/html5/html5-original.svg`,
  'CSS':              `${D}/css3/css3-original.svg`,
  'Angular':          `${D}/angularjs/angularjs-original.svg`,
  'React':            `${D}/react/react-original.svg`,
  'Vue.js':           `${D}/vuejs/vuejs-original.svg`,
  'Astro':            `${D}/astro/astro-original.svg`,
  'Bootstrap':        `${D}/bootstrap/bootstrap-original.svg`,
  'Tailwind CSS':     `${D}/tailwindcss/tailwindcss-original.svg`,
  'Chart.js':         `${D}/d3js/d3js-original.svg`,
  'Jinja2':           `${D}/jinja/jinja-original.svg`,
  'Blade':            `${D}/laravel/laravel-original.svg`,
  'Flask':            `${D}/flask/flask-original.svg`,
  'Express.js':       `${D}/express/express-original.svg`,
  'Node.js':          `${D}/nodejs/nodejs-original.svg`,
  'Laravel':          `${D}/laravel/laravel-original.svg`,
  'MySQL':            `${D}/mysql/mysql-original.svg`,
  'MongoDB':          `${D}/mongodb/mongodb-original.svg`,
  'PostgreSQL':       `${D}/postgresql/postgresql-original.svg`,
  'SQLite':           `${D}/sqlite/sqlite-original.svg`,
  'Flutter':          `${D}/flutter/flutter-original.svg`,
  'Android':          `${D}/android/android-original.svg`,
  'Pandas':           `${D}/pandas/pandas-original.svg`,
  'NumPy':            `${D}/numpy/numpy-original.svg`,
  'Matplotlib':       `${D}/matplotlib/matplotlib-original.svg`,
  'Scikit-learn':     `${D}/scikitlearn/scikitlearn-original.svg`,
  'Jupyter Notebook': `${D}/jupyter/jupyter-original.svg`,
  'Git':              `${D}/git/git-original.svg`,
  'GitHub':           `${D}/github/github-original.svg`,
  'Docker':           `${D}/docker/docker-original.svg`,
  'WordPress':        `${D}/wordpress/wordpress-original.svg`,
  'Render':           `${D}/fastapi/fastapi-original.svg`,
  'Netlify':          `${D}/netlify/netlify-original.svg`,
  'Xamarin':          `${D}/dotnetcore/dotnetcore-original.svg`,
};

export const LANG_COLOR: Record<string, string> = {
  'Python':           '#3776AB',
  'JavaScript':       '#F7DF1E',
  'TypeScript':       '#3178C6',
  'Dart':             '#00B4AB',
  'HTML':             '#E34F26',
  'Astro':            '#FF5D01',
  'Blade':            '#FF2D20',
  'PHP':              '#777BB4',
  'Jupyter Notebook': '#F37726',
  'Java':             '#007396',
  'Kotlin':           '#7F52FF',
  'Swift':            '#F05138',
  'CSS':              '#1572B6',
};
